const menuData = {
  starters: [
    {
      id: 1,
      name: "New york Hotdog",
      description: "",
      pictureUrl: require("../../assets/starters/img1.png"),
      price: "$10",
    },
    {
      id: 2,
      name: "Carolina Hotdog",
      description: "",
      pictureUrl: require("../../assets/starters/img2.png"),
      price: "$10",
    },
    {
      id: 3,
      name: "Slaw Dog",
      description: "",
      pictureUrl: require("../../assets/starters/img3.png"),
      price: "$12",
    },
  ],

  breakfast: [
    {
      id: 1,
      name: "New york Hotdog",
      description: "mustard, sauerkraut, & onion sauce",
      pictureUrl: require("../../assets/starters/img1.png"),
      price: "$10",
    },
    {
      id: 2,
      name: "Carolina Hotdog",
      description: "chili, chopped onions, & cole slaw",
      pictureUrl: require("../../assets/starters/img2.png"),
      price: "$10",
    },
    {
      id: 3,
      name: "Slaw Dog",
      description: "cole slaw, mustard",
      pictureUrl: require("../../assets/starters/img3.png"),
      price: "$12",
    },
    {
      id: 4,
      name: "Coney Island Hotdog",
      description: "cheese, chili, & chopped onions",
      pictureUrl: require("../../assets/breakfast/img1.png"),
      price: "$10",
    },
    {
      id: 5,
      name: "Memphis Dog",
      description: "bacon wrapped dog, barbecue sauce, chopped scallions, & chee",
      pictureUrl: require("../../assets/breakfast/img2.png"),
      price: "$10",
    },
    {
      id: 6,
      name: "Carolina Dog",
      description: "chili, chopped onions, & cole slaw",
      pictureUrl: require("../../assets/breakfast/img3.png"),
      price: "$10",
    },
    {
      id: 7,
      name: "Chicago Dog",
      description: "poppy seed bun, pickle spear, celery salt, tomatoes, whole pickled peppers, chopped onions, relish, and mustard ",
      pictureUrl: require("../../assets/breakfast/img4.png"),
      price: "$10",
    },
    {
      id: 8,
      name: "Foot Long Dog",
      description: "mustard & ketchup",
      pictureUrl: require("../../assets/breakfast/img1.png"),
      price: "$10",
    },
    {
      id: 9,
      name: "Vegetarian Hot Dog",
      description: "",
      pictureUrl: require("../../assets/breakfast/img2.png"),
      price: "$10",
    },
    {
      id: 10,
      name: "Polish Hot Dog",
      description: "kraut & mustard",
      pictureUrl: require("../../assets/breakfast/img3.png"),
      price: "$10",
    },
    {
      id: 11,
      name: "Italian Hot Dog",
      description: "grilled peppers & onions & mustard",
      pictureUrl: require("../../assets/breakfast/img4.png"),
      price: "$10",
    },
    {
      id: 12,
      name: "Tijuana Hot Dog",
      description: "cilantro, grilled peppers & onions & jalapenos",
      pictureUrl: require("../../assets/breakfast/img3.png"),
      price: "$10",
    },
    {
      id: 13,
      name: "Chili Cheese Hot Dog",
      description: "chili, onions, mustard, & cheese",
      pictureUrl: require("../../assets/breakfast/img4.png"),
      price: "$10",
    },
    {
      id: 14,
      name: "Rockstar Hot Dog",
      description: "make your own",
      pictureUrl: require("../../assets/breakfast/img4.png"),
      price: "$10",
    },
    {
      id: 15,
      name: "Nathan's Hot Dog",
      description: "",
      pictureUrl: require("../../assets/breakfast/img4.png"),
      price: "$10",
    },
    {
      id: 16,
      name: "Christine BG",
      description: "make your own",
      pictureUrl: require("../../assets/breakfast/img4.png"),
      price: "$10",
    },
    {
      id: 17,
      name: "All American Dog",
      description: "",
      pictureUrl: require("../../assets/breakfast/img4.png"),
      price: "$10",
    },
    {
      id: 18,
      name: "Fenway Dog",
      description: "mustard, onions, & ketchup",
      pictureUrl: require("../../assets/breakfast/img4.png"),
      price: "$10",
    },
    {
      id: 19,
      name: "Tina G",
      description: "mustard, mayo, jalapenos, ketchup",
      pictureUrl: require("../../assets/breakfast/img4.png"),
      price: "$10",
    },
    {
      id: 20,
      name: "Regular Hot Dog",
      description: "mustard & ketchup",
      pictureUrl: require("../../assets/breakfast/img4.png"),
      price: "$10",
    }
  ],

  dinner: [
    {
      id: 1,
      name: "Italian Pizza",
      description: "",
      pictureUrl: require("../../assets/dinner/img1.png"),
      price: "$20",
    },
    {
      id: 2,
      name: "Sea Curry",
      description: "",
      pictureUrl: require("../../assets/dinner/img2.png"),
      price: "$43",
    },
    {
      id: 3,
      name: "Vegan Hotdog",
      description: "",
      pictureUrl: require("../../assets/dinner/img3.png"),
      price: "$50",
    },
    {
      id: 4,
      name: "Noodle Bowl",
      description: "",
      pictureUrl: require("../../assets/dinner/img4.png"),
      price: "$40",
    },
  ],

  drinks: [
    {
      id: 1,
      name: "Panthouse Tonic",
      description: "Tomatillo, Baja Crema, Cabbage, Fried Okra",
      pictureUrl: require("../../assets/drinks/img1.png"),
      price: "$2",
    },
    {
      id: 2,
      name: "Apple Breeze",
      description: "Tomatillo, Baja Crema, Cabbage, Fried Okra",
      pictureUrl: require("../../assets/drinks/img2.png"),
      price: "$2",
    },
    {
      id: 3,
      name: "Frenchman Blitz",
      description: "Tomatillo, Baja Crema, Cabbage, Fried Okra",
      pictureUrl: require("../../assets/drinks/img3.png"),
      price: "$2",
    },
  ],
};

export default menuData;
